before:
  hooks:
    - make setup
    - go generate ./...
project_name: up-npm
release:
  github:
    owner: Icaruk
    name: up-npm
builds:
  - id: up-npm-darwin-amd64
    ldflags:
      - -s -w -X github.com/icaruk/up-npm/pkg/version.Version={{.Version}}
    binary: example
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
  - id: up-npm-linux-amd64
    ldflags:
      - -s -w -X github.com/icaruk/up-npm/pkg/version.Version={{.Version}}
    main: ./main.go
    binary: example
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: up-npm-windows-amd64
    ldflags:
      - -s -w -X github.com/icaruk/up-npm/pkg/version.Version={{.Version}}
    main: ./main.go
    binary: example
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64

checksum:
  name_template: "{{ .ProjectName }}checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"