# https://taskfile.dev

version: '3'

vars:
  DIST_FOLDER: "dist"
  APPNAME: "up-npm"
  VERSION: 3.1.1
    # sh: '{{if eq OS "windows"}}more .version{{else}}cat .version{{end}}'

tasks:
  build:
    cmds:
      - echo "Building version {{.VERSION}}"
      - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -trimpath -tags=netgo -o {{.DIST_FOLDER}}/{{.APPNAME}}-{{.VERSION}}-windows-amd64.exe
      - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -trimpath -tags=netgo -o {{.DIST_FOLDER}}/{{.APPNAME}}-{{.VERSION}}-darwin-amd64
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -trimpath -tags=netgo -o {{.DIST_FOLDER}}/{{.APPNAME}}-{{.VERSION}}-linux-amd64
      - echo "Build complete"
      - task: checksum
    silent: false
  checksum:
    cmds:
      - go run ./utils/checksum.go
    silent: false
